#!/bin/bash
# GitHub Pages Sync - Trinity MVP uses docs/ folder method

echo "📄 Trinity MVP GitHub Pages Information"
echo "======================================"
echo ""
echo "✅ GitHub Pages Configuration:"
echo "   - Method: Serves from docs/ folder on main branch"
echo "   - URL: https://jlchatha.github.io/trinity-mvp/"
echo "   - Source: docs/ directory in main repository"
echo ""
echo "✅ Documentation Status:"
echo "   - All documentation is automatically live when pushed to main"
echo "   - docs/user/user-guide.md ✅"
echo "   - docs/developer/api-reference.md ✅" 
echo "   - docs/user/quick-start.md ✅"
echo "   - docs/technical/architecture-overview.md ✅"
echo ""
echo "✅ No manual sync required - GitHub Pages updates automatically"
echo "   when docs/ folder changes are pushed to main branch"
echo ""
echo "📝 To update documentation:"
echo "   1. Edit files in trinity-mvp-working/docs/"
echo "   2. Commit and push to main branch"
echo "   3. GitHub Pages updates automatically"
echo ""
echo "🎯 Current live documentation: https://jlchatha.github.io/trinity-mvp/"